name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      (
        github.event.pull_request.author_association == 'MEMBER' ||
        github.event.pull_request.author_association == 'OWNER'
      ) &&
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: hmarr/auto-approve-action@v4
        continue-on-error: true
